services:
  app:
    build: .
    ports:
      - "3100:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://db:27017/VoiceOut
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: